"""
app.py
======
Flask orchestrator for the Smart Resume Analyzer.

Routes:
  GET  /           → upload.html  (drag-and-drop landing page)
  POST /analyze    → runs analysis, saves to SQLite history, redirects to /report
  GET  /report     → report.html  (deep-dive results)
  GET  /history    → history.html (past uploads from SQLite)

SQLite DB (resume_history.db):
  Table: uploads (id, filename, score, grade, word_count, timestamp)

Author: Senior Full-Stack Engineer (generated by Antigravity AI)
"""

import os
import sqlite3
import json
from datetime import datetime
from flask import (
    Flask, render_template, request, redirect,
    url_for, session, flash, jsonify
)
from werkzeug.utils import secure_filename
from core.analyzer import run_analysis

# ---------------------------------------------------------------------------
# App Configuration
# ---------------------------------------------------------------------------

app = Flask(__name__)
app.secret_key = "smart-resume-analyzer-secret-2024"  # Change in production

BASE_DIR     = os.path.dirname(os.path.abspath(__file__))
UPLOAD_FOLDER = os.path.join(BASE_DIR, "uploads")
DB_PATH       = os.path.join(BASE_DIR, "resume_history.db")

app.config["UPLOAD_FOLDER"] = UPLOAD_FOLDER
app.config["MAX_CONTENT_LENGTH"] = 5 * 1024 * 1024  # 5 MB limit

ALLOWED_EXTENSIONS = {"pdf", "txt"}

os.makedirs(UPLOAD_FOLDER, exist_ok=True)


# ---------------------------------------------------------------------------
# SQLite — History Database
# ---------------------------------------------------------------------------

def get_db():
    """Open a connection to the SQLite history database."""
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row  # enables dict-like access
    return conn


def init_db():
    """
    Create the uploads table if it does not already exist.
    Called once on startup.
    """
    with get_db() as conn:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS uploads (
                id         INTEGER PRIMARY KEY AUTOINCREMENT,
                filename   TEXT    NOT NULL,
                score      INTEGER NOT NULL,
                grade      TEXT    NOT NULL,
                word_count INTEGER NOT NULL,
                timestamp  TEXT    NOT NULL
            )
        """)
        conn.commit()


def record_upload(filename: str, score: int, grade: str, word_count: int):
    """Insert a new analysis result row into the history table."""
    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    with get_db() as conn:
        conn.execute(
            "INSERT INTO uploads (filename, score, grade, word_count, timestamp) "
            "VALUES (?, ?, ?, ?, ?)",
            (filename, score, grade, word_count, ts)
        )
        conn.commit()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def allowed_file(filename: str) -> bool:
    """Return True if the file extension is in the allowed set."""
    return "." in filename and filename.rsplit(".", 1)[1].lower() in ALLOWED_EXTENSIONS


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.route("/")
def index():
    """Landing page — upload form."""
    return render_template("upload.html")


@app.route("/analyze", methods=["POST"])
def analyze():
    """
    Handle the resume upload.

    Flow:
        1. Validate file presence and extension.
        2. Save securely to the uploads folder.
        3. Run the analysis pipeline.
        4. Persist a summary row to SQLite history.
        5. Store the full result in the session and redirect to /report.
    """
    if "resume" not in request.files:
        flash("No file part in the request.", "error")
        return redirect(url_for("index"))

    file = request.files["resume"]

    if file.filename == "":
        flash("No file selected.", "error")
        return redirect(url_for("index"))

    if not allowed_file(file.filename):
        flash("Unsupported file type. Please upload a PDF or TXT file.", "error")
        return redirect(url_for("index"))

    # Save file
    safe_name = secure_filename(file.filename)
    save_path = os.path.join(app.config["UPLOAD_FOLDER"], safe_name)
    file.save(save_path)

    # Run the full analysis pipeline
    try:
        result = run_analysis(save_path, safe_name)
    except Exception as e:
        flash(f"Analysis failed: {str(e)}", "error")
        return redirect(url_for("index"))

    # Persist to SQLite history
    record_upload(
        filename   = safe_name,
        score      = result["score"]["overall"],
        grade      = result["score"]["grade"],
        word_count = result["word_count"],
    )

    # Store in session (JSON-serialisable dict)
    session["result"] = result
    return redirect(url_for("report"))


@app.route("/report")
def report():
    """Display the deep-dive analysis report."""
    result = session.get("result")
    if not result:
        flash("No analysis data found. Please upload a resume.", "info")
        return redirect(url_for("index"))
    return render_template("report.html", r=result)


@app.route("/history")
def history():
    """Show upload history from SQLite."""
    with get_db() as conn:
        rows = conn.execute(
            "SELECT * FROM uploads ORDER BY id DESC LIMIT 50"
        ).fetchall()
    # Convert sqlite3.Row → plain dicts for template
    records = [dict(row) for row in rows]
    return render_template("history.html", records=records)


@app.route("/api/history")
def api_history():
    """JSON endpoint for history data (optional AJAX use)."""
    with get_db() as conn:
        rows = conn.execute(
            "SELECT * FROM uploads ORDER BY id DESC LIMIT 50"
        ).fetchall()
    return jsonify([dict(row) for row in rows])


# ---------------------------------------------------------------------------
# Entry Point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    init_db()  # Ensure the DB and table exist
    app.run(debug=True, host="0.0.0.0", port=5000)
