"""
app.py
======
Flask orchestrator for the Smart Resume Analyzer.

Routes:
  GET  /             → upload.html  (drag-and-drop landing page)
  POST /analyze      → runs analysis, saves to SQLite history, redirects to /report
  GET  /report       → report.html  (deep-dive results)
  GET  /history      → history.html (past uploads from SQLite)
  GET  /editor       → editor.html  (Smart Editor — Notion-style canvas)
  POST /download-pdf → accepts JSON {text}, returns PDF attachment

SQLite DB (resume_history.db):
  Table: uploads (id, filename, score, grade, word_count, timestamp)

Author: Senior Full-Stack Engineer (generated by Antigravity AI)
"""

import os
import io
import sqlite3
import json
from datetime import datetime
from flask import (
    Flask, render_template, request, redirect,
    url_for, session, flash, jsonify, send_file
)
from werkzeug.utils import secure_filename
from core.analyzer import run_analysis
from core.pdf_builder import generate_pdf

# ---------------------------------------------------------------------------
# App Configuration
# ---------------------------------------------------------------------------

app = Flask(__name__)
app.secret_key = "smart-resume-analyzer-secret-2024"  # Change in production

BASE_DIR     = os.path.dirname(os.path.abspath(__file__))
UPLOAD_FOLDER = os.path.join(BASE_DIR, "uploads")
DB_PATH       = os.path.join(BASE_DIR, "resume_history.db")

app.config["UPLOAD_FOLDER"] = UPLOAD_FOLDER
app.config["MAX_CONTENT_LENGTH"] = 5 * 1024 * 1024  # 5 MB limit

ALLOWED_EXTENSIONS = {"pdf", "txt"}

os.makedirs(UPLOAD_FOLDER, exist_ok=True)


# ---------------------------------------------------------------------------
# SQLite — History Database
# ---------------------------------------------------------------------------

def get_db():
    """Open a connection to the SQLite history database."""
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row  # enables dict-like access
    return conn


def init_db():
    """
    Create the uploads table if it does not already exist.
    Called once on startup.
    """
    with get_db() as conn:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS uploads (
                id         INTEGER PRIMARY KEY AUTOINCREMENT,
                filename   TEXT    NOT NULL,
                score      INTEGER NOT NULL,
                grade      TEXT    NOT NULL,
                word_count INTEGER NOT NULL,
                timestamp  TEXT    NOT NULL
            )
        """)
        conn.commit()


def record_upload(filename: str, score: int, grade: str, word_count: int):
    """Insert a new analysis result row into the history table."""
    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    with get_db() as conn:
        conn.execute(
            "INSERT INTO uploads (filename, score, grade, word_count, timestamp) "
            "VALUES (?, ?, ?, ?, ?)",
            (filename, score, grade, word_count, ts)
        )
        conn.commit()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def allowed_file(filename: str) -> bool:
    """Return True if the file extension is in the allowed set."""
    return "." in filename and filename.rsplit(".", 1)[1].lower() in ALLOWED_EXTENSIONS


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.route("/")
def index():
    """Landing page — upload form."""
    return render_template("upload.html")


@app.route("/analyze", methods=["POST"])
def analyze():
    """
    Handle the resume upload.

    Flow:
        1. Validate file presence and extension.
        2. Save securely to the uploads folder.
        3. Run the analysis pipeline.
        4. Persist a summary row to SQLite history.
        5. Store the full result in the session and redirect to /report.
    """
    if "resume" not in request.files:
        flash("No file part in the request.", "error")
        return redirect(url_for("index"))

    file = request.files["resume"]

    if file.filename == "":
        flash("No file selected.", "error")
        return redirect(url_for("index"))

    if not allowed_file(file.filename):
        flash("Unsupported file type. Please upload a PDF or TXT file.", "error")
        return redirect(url_for("index"))

    # Save file
    safe_name = secure_filename(file.filename)
    save_path = os.path.join(app.config["UPLOAD_FOLDER"], safe_name)
    file.save(save_path)

    # Run the full analysis pipeline
    try:
        result = run_analysis(save_path, safe_name)
    except Exception as e:
        flash(f"Analysis failed: {str(e)}", "error")
        return redirect(url_for("index"))

    # Persist to SQLite history
    record_upload(
        filename   = safe_name,
        score      = result["score"]["overall"],
        grade      = result["score"]["grade"],
        word_count = result["word_count"],
    )

    # Store in session (JSON-serialisable dict)
    session["result"] = result
    return redirect(url_for("report"))


@app.route("/report")
def report():
    """Display the deep-dive analysis report."""
    result = session.get("result")
    if not result:
        flash("No analysis data found. Please upload a resume.", "info")
        return redirect(url_for("index"))
    return render_template("report.html", r=result)


@app.route("/history")
def history():
    """Show upload history from SQLite."""
    with get_db() as conn:
        rows = conn.execute(
            "SELECT * FROM uploads ORDER BY id DESC LIMIT 50"
        ).fetchall()
    # Convert sqlite3.Row → plain dicts for template
    records = [dict(row) for row in rows]
    return render_template("history.html", records=records)


@app.route("/api/history")
def api_history():
    """JSON endpoint for history data (optional AJAX use)."""
    with get_db() as conn:
        rows = conn.execute(
            "SELECT * FROM uploads ORDER BY id DESC LIMIT 50"
        ).fetchall()
    return jsonify([dict(row) for row in rows])


# ---------------------------------------------------------------------------
# Smart Editor Routes
# ---------------------------------------------------------------------------

@app.route("/editor")
def editor():
    """
    Load the Smart Editor with the resume text and suggestions
    from the last analysis stored in the session.

    Passes to editor.html:
        raw_text   — the original extracted resume text
        result     — the full analysis dict (for suggestions, score, etc.)
    """
    result = session.get("result")
    if not result:
        flash("No analysis data found. Please upload a resume first.", "info")
        return redirect(url_for("index"))

    # Retrieve the stored raw text from the uploaded file path if possible;
    # otherwise reconstruct from the analysis result filename.
    raw_text_path = os.path.join(
        app.config["UPLOAD_FOLDER"],
        result.get("filename", "")
    )
    raw_text = ""
    if os.path.exists(raw_text_path):
        try:
            with open(raw_text_path, "r", encoding="utf-8", errors="ignore") as f:
                raw_text = f.read()
        except Exception:
            pass

    # Fallback: if the file was a PDF and reading it as txt fails,
    # re-run the extractor (it's cached-cheap since the file still exists).
    if not raw_text and raw_text_path.endswith(".pdf"):
        try:
            from core.analyzer import extract_text
            raw_text = extract_text(raw_text_path)
        except Exception:
            raw_text = "[Could not extract text from PDF — please paste your resume here.]"

    return render_template("editor.html", raw_text=raw_text, r=result)


@app.route("/download-pdf", methods=["POST"])
def download_pdf():
    """
    Accept the edited resume text as JSON, generate an editorial PDF,
    and return it as a file attachment.

    Request JSON: { "text": "<full resume text>" }
    Response:     PDF binary with Content-Disposition: attachment
    """
    data = request.get_json(silent=True)
    if not data or "text" not in data:
        return jsonify({"error": "No text provided."}), 400

    resume_text = data["text"].strip()
    if not resume_text:
        return jsonify({"error": "Resume text is empty."}), 400

    try:
        pdf_buffer = generate_pdf(resume_text)
    except Exception as e:
        return jsonify({"error": f"PDF generation failed: {str(e)}"}), 500

    return send_file(
        pdf_buffer,
        mimetype="application/pdf",
        as_attachment=True,
        download_name="resume_optimized.pdf",
    )


# ---------------------------------------------------------------------------
# Entry Point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    init_db()  # Ensure the DB and table exist
    app.run(debug=True, host="0.0.0.0", port=5000)
