"""
core/analyzer.py
================
The intelligence engine of the Smart Resume Analyzer.

Responsibilities:
  - PDF / TXT text extraction (pdfplumber primary, PyPDF2 fallback)
  - Contact info identification via regex (email, phone, LinkedIn)
  - Section detection (Experience, Education, Skills, etc.)
  - Weighted Resume Quality Score formula:
        Score = Σ(S_section × W_section) + (K × 2) − (D × 5)
  - Impact verb scanning for "Action Orientation"
  - Skill matching + Hard/Soft classification from skills.json
  - Three sub-scores: Readability | Skill Depth | Action Orientation

Author: Senior Full-Stack Engineer (generated by Antigravity AI)
"""

import re
import json
import os
import string
from collections import Counter


# ---------------------------------------------------------------------------
# Constants & Configuration
# ---------------------------------------------------------------------------

# Absolute path to the skills database
_SKILLS_JSON = os.path.join(os.path.dirname(__file__), "..", "data", "skills.json")

# Section keywords used by the Structure Identifier
SECTION_KEYWORDS = {
    "summary":       ["summary", "objective", "profile", "about me", "overview"],
    "experience":    ["experience", "work experience", "employment", "professional experience",
                      "internship", "career history", "work history"],
    "education":     ["education", "academic", "qualification", "degree", "university",
                      "college", "schooling"],
    "skills":        ["skills", "technical skills", "core competencies", "technologies",
                      "expertise", "proficiencies"],
    "projects":      ["projects", "personal projects", "key projects", "project work",
                      "portfolio"],
    "certifications":["certifications", "certificates", "awards", "achievements",
                      "licenses", "credentials"],
}

# Section weights for the scoring formula (must sum to 75 when all present)
SECTION_WEIGHTS = {
    "experience":     20,
    "education":      15,
    "skills":         15,
    "projects":       10,
    "certifications": 10,
    "summary":         5,
}

# Curated impact / power verbs — measures "Action Orientation"
IMPACT_VERBS = [
    "spearheaded", "orchestrated", "optimized", "architected", "engineered",
    "pioneered", "transformed", "accelerated", "amplified", "delivered",
    "executed", "launched", "implemented", "developed", "designed",
    "led", "managed", "mentored", "supervised", "coordinated",
    "collaborated", "streamlined", "automated", "reduced", "increased",
    "improved", "enhanced", "achieved", "exceeded", "generated",
    "built", "created", "established", "deployed", "integrated",
    "migrated", "resolved", "troubleshot", "analyzed", "researched",
    "presented", "published", "authored", "trained", "negotiated",
    "secured", "scaled", "refactored", "audited", "maintained",
]

# Regex patterns for contact information
REGEX_EMAIL   = r"[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}"
REGEX_PHONE   = r"(?:\+?\d{1,3}[\s\-]?)?(?:\(?\d{3,5}\)?[\s\-]?)?\d{3,5}[\s\-]?\d{4,5}"
REGEX_LINKEDIN = r"(?:https?://)?(?:www\.)?linkedin\.com/in/[\w\-]+"


# ---------------------------------------------------------------------------
# Text Extraction
# ---------------------------------------------------------------------------

def extract_text(filepath: str) -> str:
    """
    Extract raw text from a PDF or TXT file.

    Strategy:
        1. Plain .txt files are read directly.
        2. PDFs: try pdfplumber (superior table/column handling).
        3. Fallback: PyPDF2 (older PDFs / scanned-text layers).

    Returns an empty string if all methods fail.
    """
    ext = os.path.splitext(filepath)[1].lower()

    if ext == ".txt":
        with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
            return f.read()

    # --- pdfplumber (primary) ---
    try:
        import pdfplumber
        text_parts = []
        with pdfplumber.open(filepath) as pdf:
            for page in pdf.pages:
                page_text = page.extract_text()
                if page_text:
                    text_parts.append(page_text)
        if text_parts:
            return "\n".join(text_parts)
    except Exception:
        pass  # Gracefully fall through to PyPDF2

    # --- PyPDF2 (fallback) ---
    try:
        from PyPDF2 import PdfReader
        reader = PdfReader(filepath)
        text_parts = []
        for page in reader.pages:
            page_text = page.extract_text()
            if page_text:
                text_parts.append(page_text)
        return "\n".join(text_parts)
    except Exception:
        return ""


# ---------------------------------------------------------------------------
# Contact Information — Structure Identifier
# ---------------------------------------------------------------------------

def extract_contact_info(text: str) -> dict:
    """
    Dynamically identify contact information using compiled regex patterns.

    Returns a dict with keys: email, phone, linkedin.
    Values are the found string or None.
    """
    email_match    = re.search(REGEX_EMAIL, text)
    phone_match    = re.search(REGEX_PHONE, text)
    linkedin_match = re.search(REGEX_LINKEDIN, text, re.IGNORECASE)

    # Validate phone: must have at least 7 digits to avoid false positives
    phone_val = None
    if phone_match:
        digits = re.sub(r"\D", "", phone_match.group())
        if len(digits) >= 7:
            phone_val = phone_match.group().strip()

    return {
        "email":    email_match.group()    if email_match    else None,
        "phone":    phone_val,
        "linkedin": linkedin_match.group() if linkedin_match else None,
    }


# ---------------------------------------------------------------------------
# Section Detection
# ---------------------------------------------------------------------------

def detect_sections(text: str) -> dict:
    """
    Scan each line of the resume text for section headings.

    A line is treated as a section heading if it is short (< 60 chars)
    and contains one of the known section keyword groups.

    Returns a dict mapping section_name → True/False.
    """
    found = {section: False for section in SECTION_KEYWORDS}
    for line in text.split("\n"):
        stripped = line.strip().lower()
        if not stripped or len(stripped) > 60:
            continue
        for section, keywords in SECTION_KEYWORDS.items():
            if any(kw in stripped for kw in keywords):
                found[section] = True
    return found


# ---------------------------------------------------------------------------
# Skill Matching & Classification
# ---------------------------------------------------------------------------

def _load_skills_db() -> dict:
    """Load and cache skills.json from disk."""
    with open(_SKILLS_JSON, "r", encoding="utf-8") as f:
        return json.load(f)


def match_skills(text: str) -> dict:
    """
    Match skills from skills.json against the resume text.

    Returns:
        {
          "all":         [list of all unique matched skill strings],
          "by_domain":   { domain_name: [skills] },
          "hard_skills": [skills where type == 'hard'],
          "soft_skills": [skills where type == 'soft'],
          "count_hard":  int,
          "count_soft":  int,
        }
    """
    db = _load_skills_db()
    text_lower = text.lower()

    all_skills   = []
    hard_skills  = []
    soft_skills  = []
    by_domain    = {}

    for domain, meta in db.items():
        skill_type    = meta.get("type", "hard")
        domain_skills = meta.get("skills", [])
        matched       = []

        for skill in domain_skills:
            # Use word-boundary matching to avoid partial false matches
            pattern = r"\b" + re.escape(skill.lower()) + r"\b"
            if re.search(pattern, text_lower):
                matched.append(skill)
                if skill not in all_skills:
                    all_skills.append(skill)
                    if skill_type == "soft":
                        soft_skills.append(skill)
                    else:
                        hard_skills.append(skill)

        if matched:
            by_domain[domain] = matched

    return {
        "all":         all_skills,
        "by_domain":   by_domain,
        "hard_skills": hard_skills,
        "soft_skills": soft_skills,
        "count_hard":  len(hard_skills),
        "count_soft":  len(soft_skills),
    }


# ---------------------------------------------------------------------------
# Impact Verb Analysis
# ---------------------------------------------------------------------------

def analyze_impact_verbs(text: str) -> dict:
    """
    Scan the resume for impact/power verbs.

    Returns:
        {
          "found":    [list of unique impact verbs detected],
          "count":    int,
          "density":  float (verbs per 100 words),
          "score":    int  (0-100, proportional to density capped at 15 verbs/100w)
        }
    """
    words = text.lower().split()
    total_words = max(len(words), 1)  # guard division by zero

    found_verbs = []
    for verb in IMPACT_VERBS:
        pattern = r"\b" + re.escape(verb) + r"\b"
        if re.search(pattern, text.lower()):
            found_verbs.append(verb)

    verb_count = len(found_verbs)
    density    = (verb_count / total_words) * 100
    # Scale: density of 3% or more → score 100; linear below that
    score      = min(100, int((density / 3.0) * 100))

    return {
        "found":   found_verbs,
        "count":   verb_count,
        "density": round(density, 2),
        "score":   score,
    }


# ---------------------------------------------------------------------------
# Duplicate Word Penalty
# ---------------------------------------------------------------------------

def calculate_duplicate_penalty(text: str) -> int:
    """
    Compute the over-repetition penalty (D) for the scoring formula.

    Method:
        - Tokenize text, remove stopwords & punctuation.
        - Find words repeated more than 5× (likely filler words).
        - D = number of such over-used non-trivial terms (cap at 10).

    Returns an integer D used as: − (D × 5) in the score formula.
    """
    stopwords = {
        "the", "and", "is", "in", "at", "of", "a", "an", "to", "for",
        "on", "with", "as", "by", "from", "that", "this", "it", "was",
        "are", "be", "have", "has", "had", "been", "or", "but", "not",
        "my", "i", "me", "we", "our", "you", "he", "she", "they", "their",
        "will", "can", "do", "did", "time", "also", "its", "which", "all",
    }
    # Tokenise
    tokens = re.findall(r"\b[a-z]{4,}\b", text.lower())
    # Filter stopwords
    filtered = [t for t in tokens if t not in stopwords]
    freq = Counter(filtered)
    # Words used more than 5 times are flagged as repetitive filler
    overused = [word for word, count in freq.items() if count > 5]
    return min(len(overused), 10)  # cap penalty units at 10


# ---------------------------------------------------------------------------
# Master Scoring Engine
# ---------------------------------------------------------------------------

def calculate_score(sections: dict, skills_data: dict, impact_data: dict, contact: dict) -> dict:
    """
    Apply the weighted scoring formula and generate sub-scores.

    Formula:
        Score = Σ(S_section × W_section) + (K × 2) − (D × 5)

    Sub-scores (each 0–100):
        Readability       = section completeness + contact presence
        Skill Depth       = unique skill count + domain breadth
        Action Orientation = impact verb score

    Returns a dict with all score components.
    """

    # 1. Section score component Σ(S × W)
    section_score = sum(
        SECTION_WEIGHTS.get(sec, 0)
        for sec, present in sections.items()
        if present
    )

    # 2. K = unique skill count
    K = len(skills_data.get("all", []))

    # 3. Skill contribution (capped to avoid inflating beyond 30 points)
    skill_contribution = min(K * 2, 30)

    # 4. D is calculated outside; received via impact_data dict (computed caller-side)
    # We expose a small helper result here for the caller to pass D directly
    D = skills_data.get("_duplicate_penalty", 0)
    duplicate_penalty = D * 5

    # --- Raw score ---
    raw = section_score + skill_contribution - duplicate_penalty
    overall = max(0, min(100, raw))  # clamp 0–100

    # ---------------------------------------------------------------
    # Sub-scores (Readability, Skill Depth, Action Orientation)
    # ---------------------------------------------------------------

    # READABILITY: based on section coverage + contact info completeness
    sections_filled    = sum(1 for v in sections.values() if v)
    sections_total     = len(sections)
    section_pct        = (sections_filled / sections_total) * 70  # 70% weight
    contact_fields     = sum(1 for v in contact.values() if v)
    contact_pct        = (contact_fields / 3) * 30               # 30% weight
    readability_score  = int(section_pct + contact_pct)

    # SKILL DEPTH: unique skill count + domain breadth (how many domains covered)
    domain_breadth     = len(skills_data.get("by_domain", {}))
    skill_depth_score  = min(100, (K * 2) + (domain_breadth * 5))

    # ACTION ORIENTATION: directly from impact verb analysis
    action_score       = impact_data.get("score", 0)

    # ---------------------------------------------------------------
    # Label: Poor | Average | Good | Excellent
    # ---------------------------------------------------------------
    if overall >= 80:
        grade = "Excellent"
    elif overall >= 60:
        grade = "Good"
    elif overall >= 40:
        grade = "Average"
    else:
        grade = "Needs Work"

    return {
        "overall":             overall,
        "grade":               grade,
        "section_score":       section_score,
        "skill_contribution":  skill_contribution,
        "duplicate_penalty":   duplicate_penalty,
        "readability":         min(100, readability_score),
        "skill_depth":         min(100, skill_depth_score),
        "action_orientation":  action_score,
    }


# ---------------------------------------------------------------------------
# Suggestions Engine
# ---------------------------------------------------------------------------

def generate_suggestions(sections: dict, skills_data: dict,
                          impact_data: dict, contact: dict) -> list:
    """
    Produce a ranked list of actionable consultant-style improvement suggestions.

    Each suggestion is a dict:
        { "icon": str, "title": str, "body": str, "priority": "high|medium|low" }
    """
    suggestions = []

    # Missing sections
    for section, present in sections.items():
        if not present:
            weight = SECTION_WEIGHTS.get(section, 0)
            priority = "high" if weight >= 15 else "medium" if weight >= 10 else "low"
            suggestions.append({
                "icon": "📋",
                "title": f"Add a {section.capitalize()} section",
                "body": f"Your resume is missing a dedicated {section} section. "
                        f"Recruiters spend ~6 seconds scanning — make it easy for them.",
                "priority": priority,
            })

    # Contact info gaps
    if not contact.get("email"):
        suggestions.append({
            "icon": "📧",
            "title": "Include a professional email address",
            "body": "An email is the primary recruiter contact channel. "
                    "Use a firstname.lastname@domain.com format.",
            "priority": "high",
        })
    if not contact.get("phone"):
        suggestions.append({
            "icon": "📱",
            "title": "Add a phone number",
            "body": "Many recruiters prefer a quick call. A missing phone number "
                    "can slow down the hiring process.",
            "priority": "high",
        })
    if not contact.get("linkedin"):
        suggestions.append({
            "icon": "🔗",
            "title": "Link your LinkedIn profile",
            "body": "71% of recruiters screen LinkedIn before an interview. "
                    "Add your profile URL to boost credibility.",
            "priority": "medium",
        })

    # Skill count advice
    skill_count = len(skills_data.get("all", []))
    if skill_count < 8:
        suggestions.append({
            "icon": "⚡",
            "title": "Expand your skills section",
            "body": f"Only {skill_count} recognisable skill(s) detected. "
                    "Aim for 12–18 well-matched keywords to pass ATS filters.",
            "priority": "high",
        })
    elif skill_count < 14:
        suggestions.append({
            "icon": "⚡",
            "title": "Broaden your skill keywords",
            "body": f"You have {skill_count} skills listed. Adding a few more "
                    "domain-specific terms will strengthen your ATS score.",
            "priority": "medium",
        })

    # Impact verb advice
    verb_count = impact_data.get("count", 0)
    if verb_count < 5:
        suggestions.append({
            "icon": "🚀",
            "title": "Use stronger action verbs",
            "body": f"Only {verb_count} impact verb(s) found. Start bullet points "
                    "with verbs like 'Spearheaded', 'Optimized', or 'Orchestrated' "
                    "to signal ownership and leadership.",
            "priority": "high",
        })
    elif verb_count < 10:
        suggestions.append({
            "icon": "🚀",
            "title": "Increase action verb density",
            "body": "You're using some strong verbs — consider applying them "
                    "consistently to every experience bullet point.",
            "priority": "medium",
        })

    # Soft skills balance
    if skills_data.get("count_soft", 0) == 0:
        suggestions.append({
            "icon": "🤝",
            "title": "Add soft skills",
            "body": "Recruiters value both technical ability and interpersonal skills. "
                    "Mention qualities like 'Leadership', 'Collaboration', or 'Communication'.",
            "priority": "low",
        })

    # Domain diversity
    domain_count = len(skills_data.get("by_domain", {}))
    if domain_count < 2:
        suggestions.append({
            "icon": "🌐",
            "title": "Diversify your skill domains",
            "body": "Your skills appear concentrated in one domain. "
                    "Cross-functional exposure (e.g., DevOps + Cloud) is highly valued.",
            "priority": "low",
        })

    # Sort: high → medium → low
    order = {"high": 0, "medium": 1, "low": 2}
    suggestions.sort(key=lambda s: order.get(s["priority"], 3))

    return suggestions


# ---------------------------------------------------------------------------
# Master Orchestrator
# ---------------------------------------------------------------------------

def run_analysis(filepath: str, filename: str) -> dict:
    """
    Full pipeline: extract → identify → score → suggest.

    Called by app.py after a file is saved to the upload folder.

    Returns a comprehensive dict ready to be passed to the Jinja template.
    """

    # Step 1 — Extract raw text
    raw_text = extract_text(filepath)
    word_count = len(raw_text.split())

    # Step 2 — Contact info
    contact = extract_contact_info(raw_text)

    # Step 3 — Section detection
    sections = detect_sections(raw_text)

    # Step 4 — Skill matching
    skills_data = match_skills(raw_text)

    # Step 5 — Duplicate penalty (inject into skills_data for scoring)
    D = calculate_duplicate_penalty(raw_text)
    skills_data["_duplicate_penalty"] = D

    # Step 6 — Impact verbs
    impact_data = analyze_impact_verbs(raw_text)

    # Step 7 — Score
    score_data = calculate_score(sections, skills_data, impact_data, contact)

    # Step 8 — Suggestions
    suggestions = generate_suggestions(sections, skills_data, impact_data, contact)

    return {
        "filename":      filename,
        "word_count":    word_count,
        "contact":       contact,
        "sections":      sections,
        "skills":        skills_data,
        "impact":        impact_data,
        "score":         score_data,
        "suggestions":   suggestions,
        "duplicate_D":   D,
    }
